export const FETCH_FEED_DATA = "FETCH_FEED_ACCESS_LISTS_DATA";
export const FETCH_FEED_DATA_SUCCEEDED  = "FETCH_FEED_ACCESS_LISTS_DATA_SUCCEEDED";
export const FETCH_FEED_DATA_ERROR  = "FETCH_FEED_ACCESS_LISTS_DATA_ERROR";
export const UPDATE_FILTERS = "UPDATE_FILTERS_ACCESS_LISTS";