export const FETCH_FEED_DATA = "FETCH_FEED_COMPANIES_DATA";
export const FETCH_FEED_DATA_SUCCEEDED  = "FETCH_FEED_COMPANIES_DATA_SUCCEEDED";
export const FETCH_FEED_DATA_ERROR  = "FETCH_FEED_COMPANIES_DATA_ERROR";
export const UPDATE_FILTERS = "UPDATE_FILTERS_COMPANIES";