export const FETCH_FEED_DATA = "FETCH_FEED_PAYMENTS_DATA";
export const FETCH_FEED_DATA_SUCCEEDED  = "FETCH_FEED_PAYMENTS_DATA_SUCCEEDED";
export const FETCH_FEED_DATA_ERROR  = "FETCH_FEED_PAYMENTS_DATA_ERROR";
export const UPDATE_FILTERS = "UPDATE_FILTERS_PAYMENTS";
